### PR TITLE
Provide a new log msg

### PR DESCRIPTION
**Pull request by shahnaz-github**
provide a new log msg while creating a new node.

### CODE REVIEW

**Comment by shahnaz-github** [comment]
I requested a pull requested after adding a new log message  before returning any new Node. Hope this would increase readability

**Comment by nawazish-github** [comment]
@shahnaz-github  thanks for the contribution but it seems the fmt package import is missing.

**Comment by nawazish-github** [comment]
fmt package import missing

**Comment by shahnaz-github** [comment]
added fmt package import

**Pull request merged**
